FROM nginx:1.27-alpine

# Copy Nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy frontend assets
COPY frontend/templates/index.html /usr/share/nginx/html/index.html
COPY frontend/static               /usr/share/nginx/html/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
